/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package guisaint;

import config.dbConnect;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Owner
 */
public class registrationForm extends javax.swing.JFrame {

    /** Creates new form registrationForm */
    public registrationForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        Right = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ln = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pas = new javax.swing.JPasswordField();
        ct = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        fn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ps = new javax.swing.JPasswordField();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel13 = new javax.swing.JLabel();
        em1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ty = new javax.swing.JComboBox<>();
        sss = new javax.swing.JCheckBox();
        ss = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setPreferredSize(new java.awt.Dimension(900, 900));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Right.setBackground(new java.awt.Color(0, 102, 102));
        Right.setPreferredSize(new java.awt.Dimension(400, 680));

        jLabel6.setFont(new java.awt.Font("Showcard Gothic", 1, 35)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hotel Management");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("© 2025 France Adolf P. Borja. All Rights Reserved.");

        javax.swing.GroupLayout RightLayout = new javax.swing.GroupLayout(Right);
        Right.setLayout(RightLayout);
        RightLayout.setHorizontalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel7)
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        RightLayout.setVerticalGroup(
            RightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(77, 77, 77))
        );

        Main.add(Right, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 680));

        Left.setBackground(new java.awt.Color(255, 255, 255));
        Left.setMinimumSize(new java.awt.Dimension(400, 500));
        Left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create a new account ");
        Left.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        Main.add(Left, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Password");
        Main.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 90, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Last Name");
        Main.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 90, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("It’s quick and easy. ");
        Main.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        ln.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnActionPerformed(evt);
            }
        });
        Main.add(ln, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 190, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setText("Re-type Password");
        Main.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, 140, 40));

        pas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        pas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasActionPerformed(evt);
            }
        });
        Main.add(pas, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 560, 420, 50));

        ct.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctActionPerformed(evt);
            }
        });
        Main.add(ct, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 420, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel10.setText("First Name");
        Main.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 90, 40));

        fn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        fn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnActionPerformed(evt);
            }
        });
        Main.add(fn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 200, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setText("Contact");
        Main.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 90, 40));

        ps.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psActionPerformed(evt);
            }
        });
        Main.add(ps, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 420, 50));

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jToggleButton2.setText("Exit");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        Main.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 100, 50));

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jToggleButton3.setText("Sign Up");
        jToggleButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton3MouseClicked(evt);
            }
        });
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        Main.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 620, 100, 50));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setText("Type");
        Main.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 90, 40));

        em1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        em1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                em1ActionPerformed(evt);
            }
        });
        Main.add(em1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 420, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel15.setText("Email");
        Main.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 90, 40));

        ty.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        ty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "User", "Admin" }));
        ty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tyActionPerformed(evt);
            }
        });
        Main.add(ty, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 420, 50));

        sss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssActionPerformed(evt);
            }
        });
        Main.add(sss, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 40, 50));

        ss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssActionPerformed(evt);
            }
        });
        Main.add(ss, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 560, 40, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnActionPerformed

    private void pasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasActionPerformed

    private void ctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctActionPerformed

    private void fnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnActionPerformed

    private void psActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        loginForm lfm = new loginForm();
        lfm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed


dbConnect dbc = new dbConnect();

// Get input values
String firstName = fn.getText().trim();
String lastName = ln.getText().trim();
String contact = ct.getText().trim();
String userType = ty.getSelectedItem().toString();
String email = em1.getText().trim();
String password = ps.getText().trim();
String confirmPassword = pas.getText().trim();

// Regular expressions
String capitalLetterRegex = "^[A-Z][a-zA-Z]*$"; // Starts with a capital letter, followed by letters only
String emailRegex = "^[A-Z][A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$"; // Email starts with a capital letter
String contactRegex = "^[0-9]{11}$"; // Contact number must be exactly 11 digits

// Matchers
Pattern capitalPattern = Pattern.compile(capitalLetterRegex);
Matcher firstNameMatcher = capitalPattern.matcher(firstName);
Matcher lastNameMatcher = capitalPattern.matcher(lastName);
Pattern emailPattern = Pattern.compile(emailRegex);
Matcher emailMatcher = emailPattern.matcher(email);
Pattern contactPattern = Pattern.compile(contactRegex);
Matcher contactMatcher = contactPattern.matcher(contact);

// Validation checks
if (firstName.isEmpty() || lastName.isEmpty() || contact.isEmpty() || email.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
    JOptionPane.showMessageDialog(null, "All fields are required!");
} else if (!firstNameMatcher.matches()) {
    JOptionPane.showMessageDialog(null, "First name must start with a capital letter and contain only letters!");
} else if (!lastNameMatcher.matches()) {
    JOptionPane.showMessageDialog(null, "Last name must start with a capital letter and contain only letters!");
} else if (!emailMatcher.matches()) {
    JOptionPane.showMessageDialog(null, "Email must start with a capital letter and be in a valid format!");
} else if (!contactMatcher.matches()) {
    JOptionPane.showMessageDialog(null, "Contact number must be exactly 11 digits and contain only numbers!");
} else if (password.length() != 8) {  // Exactly 8 characters required
    JOptionPane.showMessageDialog(null, "Password must be exactly 8 characters long!");
} else if (!password.equals(confirmPassword)) {
    JOptionPane.showMessageDialog(null, "Passwords do not match!");
} else {
    // Insert data into the database
    String insertQuery = "INSERT INTO tabl_users (u_name, u_lname, u_contact, u_type, u_email, u_pass, status) " +
            "VALUES('" + firstName + "', '" + lastName + "', '" + contact + "', '" + userType + "', '" + email + "', '" + password + "', 'Pending')";
    
    if (dbc.insertData(insertQuery) == 0) {
        JOptionPane.showMessageDialog(null, "Registered Successfully");
    } else {
        JOptionPane.showMessageDialog(null, "Registration Failed. Please try again.");
    }
}

        
        
       
        
        
          
        
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void em1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_em1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_em1ActionPerformed

    private void tyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tyActionPerformed

    private void jToggleButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton3MouseClicked
      
        
        if(fn.getText().isEmpty() 
                && ln.getText().isEmpty()
                && em1.getText().isEmpty()
                && ct.getText().isEmpty()
                && ps.getText().isEmpty()
                && pas.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No field should be Empty!");
            
        }
    }//GEN-LAST:event_jToggleButton3MouseClicked

    private void sssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssActionPerformed

        if(sss.isSelected())
        ps.setEchoChar((char)0);
        else
         ps.setEchoChar('*');
        

    }//GEN-LAST:event_sssActionPerformed

    private void ssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssActionPerformed
 
        if(ss.isSelected())
        pas.setEchoChar((char)0);
        else
         pas.setEchoChar('*');
    }//GEN-LAST:event_ssActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Left;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Right;
    private javax.swing.JTextField ct;
    private javax.swing.JTextField em1;
    private javax.swing.JTextField fn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField ln;
    private javax.swing.JPasswordField pas;
    private javax.swing.JPasswordField ps;
    private javax.swing.JCheckBox ss;
    private javax.swing.JCheckBox sss;
    private javax.swing.JComboBox<String> ty;
    // End of variables declaration//GEN-END:variables

}
